apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: 10.100.10.2
  externalIPs:
    - "219.999.999.999"
  ports:
    -
      name: nginx
      port: 80
      targetPort: 80
    -
      name: admin
      port: 8081
      targetPort: 8081
  selector:
    app: nginx

